name: 'AutoCodeRover Bot'
description: 'Suggest patch or fix location for GitHub issues.'

runs:

  using: 'composite'
  steps:
    - uses: nus-apr/auto-code-rover@v1.0.0
      id: setup-acr
      # list the conditions when we are going to run ACR
      if: ${{ (github.event_name == 'issues' && github.event.action == 'opened') || (github.event_name == 'issue_comment' && github.event.action == 'created' && !contains(github.event.comment.body, 'open-pr')) }}

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name : Running bot
      run: |
        echo "ACR path: ${{ steps.setup-acr.outputs.ACR_PATH }}"
        cd ${{ github.action_path }}
        npm run start-ga
      shell: bash
      env:
        ACR_PATH: ${{ steps.setup-acr.outputs.ACR_PATH }}

branding:
  icon: 'code'
  color: 'blue'
