name: 'AutoCodeRover Bot'
description: 'Suggest patch or fix location for GitHub issues.'

runs:

  using: 'composite'
  steps:
    - uses: yuntongzhang/auto-code-rover@v1.0.0
      id: setup-acr

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name : Running bot
      run: |
        echo "ACR path: ${{ steps.setup-acr.outputs.acr_path }}"
        cd ${{ github.action_path }}
        npm run start-ga
      shell: bash
