name: 'AutoCodeRover Bot'
description: 'Suggest patch or fix location for GitHub issues.'

runs:
  using: 'composite'
  steps:
    - name: Clone AutoCodeRover
      run: git clone https://github.com/nus-apr/auto-code-rover.git ${{ github.action_path }}/acr && echo "clone ok"
      shell: bash

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install AutoCodeRover deps
      run: pip install -r ${{ github.action_path }}/acr/requirements.txt && echo "pip install ok"
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    # - name: Install Bot deps
    #   run: npm ci && echo "npm ci ok"
    #   shell: bash

    # - name : Running bot
    #   run: npm run start-ga # TODO: change this to GitHub Action command
    #   shell: bash

  # main: 'dist/index.js'
