name: 'AutoCodeRover Bot'
description: 'Suggest patch or fix location for GitHub issues.'

runs:

  using: 'composite'
  steps:
    # - uses: yuntongzhang/auto-code-rover@v1.0.0
    #   id: setup-acr

    - name: Clone AutoCodeRover
      id: clone-acr
      run: git clone https://github.com/nus-apr/auto-code-rover.git ${{ github.action_path }}/acr && echo "ACR_REPO=${{ github.action_path }}/acr" >> $GITHUB_OUTPUT && echo "clone ok"
      shell: bash

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        # cache: 'pip'

    - name: Install AutoCodeRover deps
      run: pip install -r ${{ steps.clone-acr.outputs.ACR_REPO }}/requirements.txt && echo "pip install ok"
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name : Running bot
      run: |
        echo "ACR path: ${{ steps.setup-acr.outputs.acr_path }}"
        cd ${{ github.action_path }}
        npm run start-ga
      shell: bash
